sudo: required
language: generic
env:
  global:
    - JOB_NAME=limited-build
    - WAF_JOBS=2

matrix:
  include:
    # Linux/gcc
    - os: linux
      dist: trusty
      env:
        - CXX=g++-4.8
        - NODE_LABELS="Linux Ubuntu Ubuntu-14.04"
        - BUILD_WITH_ASAN=yes

    # Linux/clang
    - os: linux
      dist: trusty
      env:
        - CXX=clang++
        - NODE_LABELS="Linux Ubuntu Ubuntu-14.04"
        - BUILD_WITH_ASAN=yes

    # macOS/clang
    # https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version
    - os: osx
      osx_image: xcode8.3
      env:
        - NODE_LABELS="OSX OSX-10.12"
        - BUILD_WITH_ASAN=yes

before_script:
  - ${CXX:-c++} --version
  - python --version

script:
  - ./.jenkins
